[resolve #7] gateway homologation
eamquindio/practicas_back_gateway pull request #19
Opened 2019-10-23 20:18 UTC by diegolt8

2019-10-23 20:20 UTC, Alvaro1050 approved these changes

2019-10-23 21:45 UTC, Daryl110 requested changes
por favor cambiar el estilo del codigo, gracias

2019-10-23 21:45 UTC, Daryl110 commented on app/controllers/HomologationController.js
> +};
falta salto de linea

2019-10-23 21:45 UTC, Daryl110 commented on app/services/request/HomologationServices.js
> +};
falta salto de linea

2019-10-23 21:45 UTC, Daryl110 commented on app/routes.js
> +
este salto de linea sobra

2019-10-24 16:08 UTC, diegolt8 commented on app/controllers/HomologationController.js
> +};
Resulto, gracias por la observación.

2019-10-24 16:08 UTC, diegolt8 commented on app/routes.js
> +
Resulto, gracias por la observación.

2019-10-24 16:20 UTC, Daryl110 approved these changes

2019-10-26 03:02 UTC, merged